### ISSUE TITLE
Crearea unui document unic pentru documentație

### ISSUE THREAD

**Issue by Moldoteck** [Moldoteck/EasyBooking#18]
Preluarea tuturor documentelor realizate de echipă și crearea unui singur document care cuprinde toată informația

**Comment by Moldoteck** [comment]
https://drive.google.com/file/d/1Wgpq9EBS4n0LZyyln-QvRhOPi6xn6lgV/view?usp=sharing

**Comment by Moldoteck** [comment]
https://drive.google.com/file/d/1Wgpq9EBS4n0LZyyln-QvRhOPi6xn6lgV/view?usp=sharing
Daca aveti sugestii de editare - feel free

**Comment by bodronRamona** [comment]
UPDATE: https://docs.google.com/document/d/1EXbCJV3EqNF29678zkr1X26-lT9J6nRayKcaRuWHWrE/edit?usp=sharing
