### ISSUE TITLE
Diagrame UML use-case

### ISSUE THREAD

**Issue by CarmenBoglis** [Moldoteck/EasyBooking#8]

**Comment by CarmenBoglis** [comment]
https://drive.google.com/open?id=1FqosR3XnyHsuFFBpsrVfVjrPaAS9-LdCOnFx63u6E68

**Comment by CarmenBoglis** [comment]
![uml use-case diagram](https://user-images.githubusercontent.com/37275862/37557371-323983b4-2a0c-11e8-8462-04588904b85f.jpg)

**Comment by CarmenBoglis** [comment]
Descrierea diagramei:
[Explicații diagrama use-case .docx](https://github.com/Moldoteck/TeamProject/files/1821887/Explica.ii.diagrama.use-case.docx)

Pentru sugestii, puteți adăuga comentarii direct pe text aici:
https://drive.google.com/open?id=1h8VQ1jGYZKCx1yv2WwCJz5L3NobnUj-UtXG-qHiK68c

**Comment by Moldoteck** [comment]
trebuie de adaugat si use-case de Register

**Comment by bodronRamona** [comment]
@CarmenBoglis
